server:
  port: 8283 #${PORT:0} #Generar puertos aleatorios.
  address: 192.168.26.71

spring:
  application:
    name: officedepot-services

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

external:
  property: Prueba de configuracion (ConfigServer, EurekaServer, ZuulProxy)!!!!!!

property:
  ipAddress: 192.168.26.71
  patterns: /**

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream, info, health

app:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost;databaseName=antiFraudDB
    username: anti-fraudes
    password: Admin010

